namespace Iskra.Desktop;

/// <summary>
/// Settings, GitHub sign-in, update-check, cloud-log, and history-export text.
/// Split from the core catalog purely for file size; both halves are merged in
/// <see cref="DesktopLocalization.Catalogs"/> and validated for completeness.
/// </summary>
public static partial class DesktopLocalization
{
    private static readonly (DesktopTextKey Key, string Value)[] UkrainianExtended =
    [
        // --- generic actions ---
        (DesktopTextKey.Cancel, "Скасувати"),
        (DesktopTextKey.ActionRefresh, "Оновити"),
        (DesktopTextKey.ActionSave, "Зберегти"),
        (DesktopTextKey.ActionReset, "Типові значення"),
        (DesktopTextKey.ActionBrowse, "Огляд…"),
        (DesktopTextKey.ActionCheck, "Перевірити"),
        (DesktopTextKey.ActionCheckUpdates, "Перевірити оновлення"),
        (DesktopTextKey.ActionOpenRelease, "Відкрити реліз"),
        (DesktopTextKey.ActionUploadNow, "Вивантажити зараз"),
        (DesktopTextKey.ActionSignOut, "Вийти"),

        // --- settings sections and labels ---
        (DesktopTextKey.SettingsSectionCatalog, "Каталог"),
        (DesktopTextKey.SettingsCatalogPath, "Шлях до каталогу"),
        (DesktopTextKey.SettingsSignatureRequired, "Вимагати підпис"),
        (DesktopTextKey.SettingsSignatureRequiredContent, "Приймати лише каталог із дійсним підписом Ed25519"),
        (DesktopTextKey.SettingsSignatureMandatory, "У цій збірці підпис обов'язковий і не може бути вимкнений."),
        (DesktopTextKey.SettingsSectionCatalogUpdate, "Каталог GitHub (авто-оновлення)"),
        (DesktopTextKey.SettingsAutoUpdate, "Авто-оновлення"),
        (DesktopTextKey.SettingsAutoUpdateContent, "Перевіряти офіційний каталог під час запуску"),
        (DesktopTextKey.SettingsLockedSource, "Заблоковане джерело"),
        (DesktopTextKey.SettingsSectionAppUpdate, "Оновлення застосунку"),
        (DesktopTextKey.SettingsCurrentVersion, "Поточна версія"),
        (DesktopTextKey.SettingsReleases, "Релізи"),
        (DesktopTextKey.SettingsStatus, "Стан"),
        (DesktopTextKey.SettingsSectionGitHubAuth, "Авторизація GitHub"),
        (DesktopTextKey.SettingsSectionDebugger, "Програматор / BMP"),
        (DesktopTextKey.SettingsGdbPath, "Шлях до gdb"),
        (DesktopTextKey.SettingsSwdFrequency, "Частота SWD (Гц)"),
        (DesktopTextKey.SettingsPower, "Живлення"),
        (DesktopTextKey.SettingsPowerExternal, "Зовнішнє"),
        (DesktopTextKey.SettingsPowerProbe, "Від програматора (tpwr)"),
        (DesktopTextKey.SettingsConnectReset, "Скидання при підключенні"),
        (DesktopTextKey.SettingsConnectResetContent, "Вмикати connect_rst перед скануванням"),
        (DesktopTextKey.SettingsTimeout, "Тайм-аут (с)"),
        (DesktopTextKey.SettingsSectionLogStation, "Журнал і станція"),
        (DesktopTextKey.SettingsLogFile, "Файл журналу"),
        (DesktopTextKey.SettingsStationId, "ID станції"),
        (DesktopTextKey.SettingsSectionOperatorUi, "Інтерфейс оператора"),
        (DesktopTextKey.SettingsHotkey, "Гаряча клавіша"),
        (DesktopTextKey.SettingsSectionCloudLog, "Хмарний журнал (iskra-logs)"),
        (DesktopTextKey.SettingsCloudAutoUpload, "Вивантажувати журнал автоматично"),
        (DesktopTextKey.SettingsCloudInterval, "Інтервал (хв)"),
        (DesktopTextKey.SettingsCloudPrivateKey, "Приватний ключ (.pem)"),
        (DesktopTextKey.SettingsBatches, "Партії"),
        (DesktopTextKey.SettingsBatchesContent, "Увімкнути режим партій і локальне блокування"),
        (DesktopTextKey.SettingsRepository, "Репозиторій"),
        (DesktopTextKey.HotkeyDisabled, "Вимкнено"),
        (DesktopTextKey.SettingsAutoSaveNote, "Зміни зберігаються автоматично, коли ви залишаєте вкладку або закриваєте вікно."),

        // --- settings status ---
        (DesktopTextKey.SettingsSaved, "✓ Збережено"),
        (DesktopTextKey.SettingsUnsaved, "Є незбережені зміни"),
        (DesktopTextKey.SettingsNoChanges, "Змін немає"),
        (DesktopTextKey.SettingsResetNotice, "Відновлено типові значення — натисніть «Зберегти», щоб застосувати"),
        (DesktopTextKey.SettingsInvalidField, "✗ Некоректне значення: {0}. Потрібне ціле число більше за нуль."),
        (DesktopTextKey.SettingsSaveFailed, "✗ Не вдалося зберегти: {0}"),

        // --- file dialogs ---
        (DesktopTextKey.DialogCatalogTitle, "Виберіть catalog.json"),
        (DesktopTextKey.DialogFilterCatalog, "Каталог JSON"),
        (DesktopTextKey.DialogGdbTitle, "Виберіть arm-none-eabi-gdb"),
        (DesktopTextKey.DialogFilterGdb, "Виконуваний файл gdb"),
        (DesktopTextKey.DialogLogTitle, "Виберіть файл журналу SQLite"),
        (DesktopTextKey.DialogFilterSqlite, "База даних SQLite"),
        (DesktopTextKey.DialogPemTitle, "Виберіть приватний ключ .pem"),
        (DesktopTextKey.DialogFilterPem, "Приватний ключ PEM"),
        (DesktopTextKey.DialogExportTitle, "Зберегти CSV"),
        (DesktopTextKey.DialogFilterCsv, "CSV"),
        (DesktopTextKey.DialogUnavailable, "✗ Діалог недоступний у цьому вікні."),

        // --- GitHub auth ---
        (DesktopTextKey.AuthSignIn, "Увійти в GitHub"),
        (DesktopTextKey.AuthUnsupportedPlatform, "Вхід GitHub доступний лише у Windows: на інших системах немає зашифрованого сховища токенів."),
        (DesktopTextKey.AuthClientMissing, "✗ Client ID застосунку GitHub не налаштовано у цій збірці."),
        (DesktopTextKey.AuthNotSignedIn, "Не виконано вхід"),
        (DesktopTextKey.AuthSessionExpired, "✗ Сесію GitHub протерміновано — увійдіть знову."),
        (DesktopTextKey.AuthAccessValid, "токен дійсний"),
        (DesktopTextKey.AuthAccessRefresh, "токен буде оновлено"),
        (DesktopTextKey.AuthSignedIn, "✓ Вхід виконано ({0}, до {1})"),
        (DesktopTextKey.AuthTokenCorrupt, "✗ Сховище токенів пошкоджено: {0}"),
        (DesktopTextKey.AuthDeviceCodeFailed, "Не вдалося отримати код пристрою: {0}"),
        (DesktopTextKey.AuthSaveFailed, "Не вдалося зберегти токен: {0}"),
        (DesktopTextKey.AuthDeleteFailed, "✗ Не вдалося видалити токен: {0}"),
        (DesktopTextKey.AuthRefreshFailed, "✗ Не вдалося оновити токен: {0}"),

        // --- device flow dialog ---
        (DesktopTextKey.DeviceTitle, "Підключення станції до GitHub"),
        (DesktopTextKey.DeviceStep1, "Крок 1. Відкрийте цю адресу в браузері:"),
        (DesktopTextKey.DeviceStep2, "Крок 2. Введіть цей код:"),
        (DesktopTextKey.DeviceOpenBrowser, "Відкрити"),
        (DesktopTextKey.DeviceCopyCode, "Копіювати"),
        (DesktopTextKey.DeviceWaiting, "Очікування підтвердження в браузері…"),
        (DesktopTextKey.DeviceCodeCopied, "✓ Код скопійовано"),
        (DesktopTextKey.DeviceCopyFailed, "Не вдалося скопіювати: {0}"),
        (DesktopTextKey.DeviceBrowserFailed, "Не вдалося відкрити браузер: {0}"),
        (DesktopTextKey.DeviceAccessDenied, "Доступ відхилено в GitHub."),
        (DesktopTextKey.DeviceCodeExpired, "Термін дії коду минув. Спробуйте ще раз."),
        (DesktopTextKey.DeviceError, "Помилка: {0}"),

        // --- updates ---
        (DesktopTextKey.UpdateChecking, "Перевірка…"),
        (DesktopTextKey.CatalogUpdated, "✓ Каталог оновлено до {0}"),
        (DesktopTextKey.CatalogUpdateAvailable, "Доступний новіший підписаний каталог ({0}). Натисніть «Перезавантажити», щоб застосувати."),
        (DesktopTextKey.TargetDetail, "{0} · {1} · {2} КБ · початок флеш {3}"),
        (DesktopTextKey.CatalogDefaultBadge, "ТИПОВИЙ"),
        (DesktopTextKey.CatalogRevokedBadge, "ВІДКЛИКАНО"),
        (DesktopTextKey.CatalogRemoteBadge, "GITHUB"),
        (DesktopTextKey.FullScreenTooltip, "Повний екран (F11). Вихід — F11 або Esc."),
        (DesktopTextKey.CatalogUpToDate, "✓ Каталог актуальний ({0})"),
        (DesktopTextKey.CatalogNoRelease, "Релізів каталогу ще немає."),
        (DesktopTextKey.CatalogNetworkError, "Помилка мережі — перевірте з'єднання."),
        (DesktopTextKey.CatalogBadSignature, "✗ Підпис каталогу недійсний. Каталог відхилено."),
        (DesktopTextKey.CatalogAssetsMissing, "✗ У релізі немає catalog.json та підпису."),
        (DesktopTextKey.CatalogParseError, "✗ Не вдалося розібрати каталог."),
        (DesktopTextKey.CatalogSourceNotAllowed, "✗ Джерело каталогу не входить до дозволених."),
        (DesktopTextKey.CatalogRollbackRejected, "✗ Відхилено: каталог старіший за вже прийнятий."),
        (DesktopTextKey.AppUpdateAvailable, "✓ Доступна версія {0}"),
        (DesktopTextKey.AppUpToDate, "✓ Встановлено найновішу версію"),
        (DesktopTextKey.AppNoRelease, "Релізів застосунку ще немає."),
        (DesktopTextKey.AppUpdateParseError, "✗ Не вдалося прочитати дані релізу."),

        // --- cloud log ---
        (DesktopTextKey.CloudDisabledShort, "вимкнено"),
        (DesktopTextKey.CloudDisabledDetail, "Вивантаження журналу вимкнено в налаштуваннях."),
        (DesktopTextKey.CloudUnconfiguredShort, "не налаштовано"),
        (DesktopTextKey.CloudUnconfiguredDetail, "Застосунок GitHub для журналів не налаштовано у цій збірці."),
        (DesktopTextKey.CloudEmptyShort, "порожньо"),
        (DesktopTextKey.CloudEmptyDetail, "Локальний журнал ще не створено."),
        (DesktopTextKey.CloudSyncedShort, "✓ синхр."),
        (DesktopTextKey.CloudQueuedShort, "{0} у черзі"),
        (DesktopTextKey.CloudErrorShort, "помилка"),
        (DesktopTextKey.CloudUploadedAll, "Усі рядки вивантажено."),
        (DesktopTextKey.CloudRowsWaiting, "Очікують вивантаження: {0}"),
        (DesktopTextKey.CloudEnableFirst, "Спершу увімкніть хмарний журнал."),
        (DesktopTextKey.CloudKeyMissing, "✗ Файл ключа не знайдено: {0}"),
        (DesktopTextKey.CloudUploading, "Вивантаження…"),
        (DesktopTextKey.CloudUploadReport, "✓ Рядків: {0}; створено файлів: {1}; оновлено: {2}; залишилось: {3}"),

        // --- history ---
        (DesktopTextKey.HistoryExportBatch, "Експорт CSV (партія)"),
        (DesktopTextKey.HistoryExportAll, "Експорт CSV (все)"),
        (DesktopTextKey.RecentAttempts, "Останні спроби: {0}"),
        (DesktopTextKey.HistoryBatchEmpty, "Партія {0}: спроб ще немає."),
        (DesktopTextKey.HistoryBatchCounts, "Партія {0}: усього {1}, PASS {2}, FAIL {3} ({4})"),
        (DesktopTextKey.HistoryNeedBatch, "Введіть ID партії, щоб побачити підсумок. Записів у журналі: {0}"),
        (DesktopTextKey.HistoryNoBatches, "Режим партій вимкнено. Записів у журналі: {0}"),
        (DesktopTextKey.ExportDone, "✓ Експортовано рядків: {0} → {1}"),
        (DesktopTextKey.ExportBatchesDisabled, "Режим партій вимкнено — експортуйте весь журнал."),
        (DesktopTextKey.ExportBatchRequired, "Спершу введіть ID партії."),
        (DesktopTextKey.ExportNoDatabase, "Журнал ще не створено."),
    ];

    private static readonly (DesktopTextKey Key, string Value)[] EnglishExtended =
    [
        (DesktopTextKey.Cancel, "Cancel"),
        (DesktopTextKey.ActionRefresh, "Refresh"),
        (DesktopTextKey.ActionSave, "Save"),
        (DesktopTextKey.ActionReset, "Restore defaults"),
        (DesktopTextKey.ActionBrowse, "Browse…"),
        (DesktopTextKey.ActionCheck, "Check"),
        (DesktopTextKey.ActionCheckUpdates, "Check for updates"),
        (DesktopTextKey.ActionOpenRelease, "Open release"),
        (DesktopTextKey.ActionUploadNow, "Upload now"),
        (DesktopTextKey.ActionSignOut, "Sign out"),

        (DesktopTextKey.SettingsSectionCatalog, "Catalog"),
        (DesktopTextKey.SettingsCatalogPath, "Catalog path"),
        (DesktopTextKey.SettingsSignatureRequired, "Require signature"),
        (DesktopTextKey.SettingsSignatureRequiredContent, "Accept only a catalog with a valid Ed25519 signature"),
        (DesktopTextKey.SettingsSignatureMandatory, "Signature verification is mandatory in this build and cannot be turned off."),
        (DesktopTextKey.SettingsSectionCatalogUpdate, "GitHub catalog (auto-update)"),
        (DesktopTextKey.SettingsAutoUpdate, "Auto-update"),
        (DesktopTextKey.SettingsAutoUpdateContent, "Check the official catalog at startup"),
        (DesktopTextKey.SettingsLockedSource, "Locked source"),
        (DesktopTextKey.SettingsSectionAppUpdate, "Application update"),
        (DesktopTextKey.SettingsCurrentVersion, "Current version"),
        (DesktopTextKey.SettingsReleases, "Releases"),
        (DesktopTextKey.SettingsStatus, "Status"),
        (DesktopTextKey.SettingsSectionGitHubAuth, "GitHub sign-in"),
        (DesktopTextKey.SettingsSectionDebugger, "Probe / BMP"),
        (DesktopTextKey.SettingsGdbPath, "gdb path"),
        (DesktopTextKey.SettingsSwdFrequency, "SWD frequency (Hz)"),
        (DesktopTextKey.SettingsPower, "Power"),
        (DesktopTextKey.SettingsPowerExternal, "External"),
        (DesktopTextKey.SettingsPowerProbe, "From the probe (tpwr)"),
        (DesktopTextKey.SettingsConnectReset, "Connect under reset"),
        (DesktopTextKey.SettingsConnectResetContent, "Enable connect_rst before scanning"),
        (DesktopTextKey.SettingsTimeout, "Timeout (s)"),
        (DesktopTextKey.SettingsSectionLogStation, "Log and station"),
        (DesktopTextKey.SettingsLogFile, "Log file"),
        (DesktopTextKey.SettingsStationId, "Station ID"),
        (DesktopTextKey.SettingsSectionOperatorUi, "Operator interface"),
        (DesktopTextKey.SettingsHotkey, "Hotkey"),
        (DesktopTextKey.SettingsSectionCloudLog, "Cloud log (iskra-logs)"),
        (DesktopTextKey.SettingsCloudAutoUpload, "Upload the log automatically"),
        (DesktopTextKey.SettingsCloudInterval, "Interval (min)"),
        (DesktopTextKey.SettingsCloudPrivateKey, "Private key (.pem)"),
        (DesktopTextKey.SettingsBatches, "Batches"),
        (DesktopTextKey.SettingsBatchesContent, "Enable batch mode and local locking"),
        (DesktopTextKey.SettingsRepository, "Repository"),
        (DesktopTextKey.HotkeyDisabled, "Disabled"),
        (DesktopTextKey.SettingsAutoSaveNote, "Changes are saved automatically when you leave the tab or close the window."),

        (DesktopTextKey.SettingsSaved, "✓ Saved"),
        (DesktopTextKey.SettingsUnsaved, "Unsaved changes"),
        (DesktopTextKey.SettingsNoChanges, "No changes"),
        (DesktopTextKey.SettingsResetNotice, "Defaults restored — press Save to apply"),
        (DesktopTextKey.SettingsInvalidField, "✗ Invalid value: {0}. A whole number greater than zero is required."),
        (DesktopTextKey.SettingsSaveFailed, "✗ Could not save: {0}"),

        (DesktopTextKey.DialogCatalogTitle, "Select catalog.json"),
        (DesktopTextKey.DialogFilterCatalog, "Catalog JSON"),
        (DesktopTextKey.DialogGdbTitle, "Select arm-none-eabi-gdb"),
        (DesktopTextKey.DialogFilterGdb, "gdb executable"),
        (DesktopTextKey.DialogLogTitle, "Select the SQLite log file"),
        (DesktopTextKey.DialogFilterSqlite, "SQLite database"),
        (DesktopTextKey.DialogPemTitle, "Select the .pem private key"),
        (DesktopTextKey.DialogFilterPem, "PEM private key"),
        (DesktopTextKey.DialogExportTitle, "Save CSV"),
        (DesktopTextKey.DialogFilterCsv, "CSV"),
        (DesktopTextKey.DialogUnavailable, "✗ Dialogs are not available from this window."),

        (DesktopTextKey.AuthSignIn, "Sign in to GitHub"),
        (DesktopTextKey.AuthUnsupportedPlatform, "GitHub sign-in is Windows-only: no encrypted token store exists on other systems yet."),
        (DesktopTextKey.AuthClientMissing, "✗ The GitHub App client ID is not configured in this build."),
        (DesktopTextKey.AuthNotSignedIn, "Not signed in"),
        (DesktopTextKey.AuthSessionExpired, "✗ The GitHub session expired — sign in again."),
        (DesktopTextKey.AuthAccessValid, "token valid"),
        (DesktopTextKey.AuthAccessRefresh, "token will refresh"),
        (DesktopTextKey.AuthSignedIn, "✓ Signed in ({0}, until {1})"),
        (DesktopTextKey.AuthTokenCorrupt, "✗ The token store is corrupt: {0}"),
        (DesktopTextKey.AuthDeviceCodeFailed, "Could not request a device code: {0}"),
        (DesktopTextKey.AuthSaveFailed, "Could not save the token: {0}"),
        (DesktopTextKey.AuthDeleteFailed, "✗ Could not delete the token: {0}"),
        (DesktopTextKey.AuthRefreshFailed, "✗ Could not refresh the token: {0}"),

        (DesktopTextKey.DeviceTitle, "Connect this station to GitHub"),
        (DesktopTextKey.DeviceStep1, "Step 1. Open this address in a browser:"),
        (DesktopTextKey.DeviceStep2, "Step 2. Enter this code:"),
        (DesktopTextKey.DeviceOpenBrowser, "Open"),
        (DesktopTextKey.DeviceCopyCode, "Copy"),
        (DesktopTextKey.DeviceWaiting, "Waiting for confirmation in the browser…"),
        (DesktopTextKey.DeviceCodeCopied, "✓ Code copied"),
        (DesktopTextKey.DeviceCopyFailed, "Could not copy: {0}"),
        (DesktopTextKey.DeviceBrowserFailed, "Could not open the browser: {0}"),
        (DesktopTextKey.DeviceAccessDenied, "Access was denied on GitHub."),
        (DesktopTextKey.DeviceCodeExpired, "The code expired. Try again."),
        (DesktopTextKey.DeviceError, "Error: {0}"),

        (DesktopTextKey.UpdateChecking, "Checking…"),
        (DesktopTextKey.CatalogUpdated, "✓ Catalog updated to {0}"),
        (DesktopTextKey.CatalogUpdateAvailable, "A newer signed catalog is available ({0}). Press Reload to apply it."),
        (DesktopTextKey.TargetDetail, "{0} · {1} · {2} KB · flash origin {3}"),
        (DesktopTextKey.CatalogDefaultBadge, "DEFAULT"),
        (DesktopTextKey.CatalogRevokedBadge, "REVOKED"),
        (DesktopTextKey.CatalogRemoteBadge, "GITHUB"),
        (DesktopTextKey.FullScreenTooltip, "Full screen (F11). Leave with F11 or Esc."),
        (DesktopTextKey.CatalogUpToDate, "✓ Catalog is up to date ({0})"),
        (DesktopTextKey.CatalogNoRelease, "No catalog release exists yet."),
        (DesktopTextKey.CatalogNetworkError, "Network error — check the connection."),
        (DesktopTextKey.CatalogBadSignature, "✗ The catalog signature is invalid. The catalog was rejected."),
        (DesktopTextKey.CatalogAssetsMissing, "✗ The release has no catalog.json and signature."),
        (DesktopTextKey.CatalogParseError, "✗ The catalog could not be parsed."),
        (DesktopTextKey.CatalogSourceNotAllowed, "✗ The catalog source is not in the allowlist."),
        (DesktopTextKey.CatalogRollbackRejected, "✗ Rejected: the catalog is older than the one already accepted."),
        (DesktopTextKey.AppUpdateAvailable, "✓ Version {0} is available"),
        (DesktopTextKey.AppUpToDate, "✓ The latest version is installed"),
        (DesktopTextKey.AppNoRelease, "No application release exists yet."),
        (DesktopTextKey.AppUpdateParseError, "✗ The release data could not be read."),

        (DesktopTextKey.CloudDisabledShort, "disabled"),
        (DesktopTextKey.CloudDisabledDetail, "Log upload is disabled in Settings."),
        (DesktopTextKey.CloudUnconfiguredShort, "not configured"),
        (DesktopTextKey.CloudUnconfiguredDetail, "The GitHub App for logs is not configured in this build."),
        (DesktopTextKey.CloudEmptyShort, "empty"),
        (DesktopTextKey.CloudEmptyDetail, "The local log has not been created yet."),
        (DesktopTextKey.CloudSyncedShort, "✓ synced"),
        (DesktopTextKey.CloudQueuedShort, "{0} queued"),
        (DesktopTextKey.CloudErrorShort, "error"),
        (DesktopTextKey.CloudUploadedAll, "All rows uploaded."),
        (DesktopTextKey.CloudRowsWaiting, "Rows waiting to upload: {0}"),
        (DesktopTextKey.CloudEnableFirst, "Enable the cloud log first."),
        (DesktopTextKey.CloudKeyMissing, "✗ Key file not found: {0}"),
        (DesktopTextKey.CloudUploading, "Uploading…"),
        (DesktopTextKey.CloudUploadReport, "✓ Rows: {0}; files created: {1}; updated: {2}; leftover: {3}"),

        (DesktopTextKey.HistoryExportBatch, "Export CSV (batch)"),
        (DesktopTextKey.HistoryExportAll, "Export CSV (all)"),
        (DesktopTextKey.RecentAttempts, "Recent attempts: {0}"),
        (DesktopTextKey.HistoryBatchEmpty, "Batch {0}: no attempts yet."),
        (DesktopTextKey.HistoryBatchCounts, "Batch {0}: total {1}, PASS {2}, FAIL {3} ({4})"),
        (DesktopTextKey.HistoryNeedBatch, "Enter a batch ID to see its summary. Rows in the log: {0}"),
        (DesktopTextKey.HistoryNoBatches, "Batch mode is disabled. Rows in the log: {0}"),
        (DesktopTextKey.ExportDone, "✓ Exported {0} rows → {1}"),
        (DesktopTextKey.ExportBatchesDisabled, "Batch mode is disabled — export the whole log instead."),
        (DesktopTextKey.ExportBatchRequired, "Enter a batch ID first."),
        (DesktopTextKey.ExportNoDatabase, "The log has not been created yet."),
    ];

    private static readonly (DesktopTextKey Key, string Value)[] GermanExtended =
    [
        (DesktopTextKey.Cancel, "Abbrechen"),
        (DesktopTextKey.ActionRefresh, "Aktualisieren"),
        (DesktopTextKey.ActionSave, "Speichern"),
        (DesktopTextKey.ActionReset, "Standardwerte"),
        (DesktopTextKey.ActionBrowse, "Durchsuchen…"),
        (DesktopTextKey.ActionCheck, "Prüfen"),
        (DesktopTextKey.ActionCheckUpdates, "Nach Updates suchen"),
        (DesktopTextKey.ActionOpenRelease, "Release öffnen"),
        (DesktopTextKey.ActionUploadNow, "Jetzt hochladen"),
        (DesktopTextKey.ActionSignOut, "Abmelden"),

        (DesktopTextKey.SettingsSectionCatalog, "Katalog"),
        (DesktopTextKey.SettingsCatalogPath, "Katalogpfad"),
        (DesktopTextKey.SettingsSignatureRequired, "Signatur verlangen"),
        (DesktopTextKey.SettingsSignatureRequiredContent, "Nur einen Katalog mit gültiger Ed25519-Signatur akzeptieren"),
        (DesktopTextKey.SettingsSignatureMandatory, "Die Signaturprüfung ist in diesem Build verpflichtend und kann nicht deaktiviert werden."),
        (DesktopTextKey.SettingsSectionCatalogUpdate, "GitHub-Katalog (Auto-Update)"),
        (DesktopTextKey.SettingsAutoUpdate, "Auto-Update"),
        (DesktopTextKey.SettingsAutoUpdateContent, "Den offiziellen Katalog beim Start prüfen"),
        (DesktopTextKey.SettingsLockedSource, "Gesperrte Quelle"),
        (DesktopTextKey.SettingsSectionAppUpdate, "Anwendungs-Update"),
        (DesktopTextKey.SettingsCurrentVersion, "Aktuelle Version"),
        (DesktopTextKey.SettingsReleases, "Releases"),
        (DesktopTextKey.SettingsStatus, "Status"),
        (DesktopTextKey.SettingsSectionGitHubAuth, "GitHub-Anmeldung"),
        (DesktopTextKey.SettingsSectionDebugger, "Programmiergerät / BMP"),
        (DesktopTextKey.SettingsGdbPath, "gdb-Pfad"),
        (DesktopTextKey.SettingsSwdFrequency, "SWD-Frequenz (Hz)"),
        (DesktopTextKey.SettingsPower, "Stromversorgung"),
        (DesktopTextKey.SettingsPowerExternal, "Extern"),
        (DesktopTextKey.SettingsPowerProbe, "Über die Sonde (tpwr)"),
        (DesktopTextKey.SettingsConnectReset, "Verbinden mit Reset"),
        (DesktopTextKey.SettingsConnectResetContent, "connect_rst vor dem Scan aktivieren"),
        (DesktopTextKey.SettingsTimeout, "Zeitlimit (s)"),
        (DesktopTextKey.SettingsSectionLogStation, "Protokoll und Station"),
        (DesktopTextKey.SettingsLogFile, "Protokolldatei"),
        (DesktopTextKey.SettingsStationId, "Stations-ID"),
        (DesktopTextKey.SettingsSectionOperatorUi, "Bedienoberfläche"),
        (DesktopTextKey.SettingsHotkey, "Tastenkürzel"),
        (DesktopTextKey.SettingsSectionCloudLog, "Cloud-Protokoll (iskra-logs)"),
        (DesktopTextKey.SettingsCloudAutoUpload, "Protokoll automatisch hochladen"),
        (DesktopTextKey.SettingsCloudInterval, "Intervall (Min.)"),
        (DesktopTextKey.SettingsCloudPrivateKey, "Privater Schlüssel (.pem)"),
        (DesktopTextKey.SettingsBatches, "Chargen"),
        (DesktopTextKey.SettingsBatchesContent, "Chargenmodus und lokale Sperre aktivieren"),
        (DesktopTextKey.SettingsRepository, "Repository"),
        (DesktopTextKey.HotkeyDisabled, "Deaktiviert"),
        (DesktopTextKey.SettingsAutoSaveNote, "Änderungen werden automatisch gespeichert, wenn Sie den Tab verlassen oder das Fenster schließen."),

        (DesktopTextKey.SettingsSaved, "✓ Gespeichert"),
        (DesktopTextKey.SettingsUnsaved, "Nicht gespeicherte Änderungen"),
        (DesktopTextKey.SettingsNoChanges, "Keine Änderungen"),
        (DesktopTextKey.SettingsResetNotice, "Standardwerte wiederhergestellt — zum Übernehmen «Speichern» drücken"),
        (DesktopTextKey.SettingsInvalidField, "✗ Ungültiger Wert: {0}. Erforderlich ist eine ganze Zahl größer als null."),
        (DesktopTextKey.SettingsSaveFailed, "✗ Speichern fehlgeschlagen: {0}"),

        (DesktopTextKey.DialogCatalogTitle, "catalog.json auswählen"),
        (DesktopTextKey.DialogFilterCatalog, "Katalog-JSON"),
        (DesktopTextKey.DialogGdbTitle, "arm-none-eabi-gdb auswählen"),
        (DesktopTextKey.DialogFilterGdb, "gdb-Programmdatei"),
        (DesktopTextKey.DialogLogTitle, "SQLite-Protokolldatei auswählen"),
        (DesktopTextKey.DialogFilterSqlite, "SQLite-Datenbank"),
        (DesktopTextKey.DialogPemTitle, "Privaten .pem-Schlüssel auswählen"),
        (DesktopTextKey.DialogFilterPem, "Privater PEM-Schlüssel"),
        (DesktopTextKey.DialogExportTitle, "CSV speichern"),
        (DesktopTextKey.DialogFilterCsv, "CSV"),
        (DesktopTextKey.DialogUnavailable, "✗ Dialoge sind aus diesem Fenster nicht verfügbar."),

        (DesktopTextKey.AuthSignIn, "Bei GitHub anmelden"),
        (DesktopTextKey.AuthUnsupportedPlatform, "Die GitHub-Anmeldung gibt es nur unter Windows: auf anderen Systemen existiert noch kein verschlüsselter Token-Speicher."),
        (DesktopTextKey.AuthClientMissing, "✗ Die GitHub-App-Client-ID ist in diesem Build nicht konfiguriert."),
        (DesktopTextKey.AuthNotSignedIn, "Nicht angemeldet"),
        (DesktopTextKey.AuthSessionExpired, "✗ Die GitHub-Sitzung ist abgelaufen — bitte erneut anmelden."),
        (DesktopTextKey.AuthAccessValid, "Token gültig"),
        (DesktopTextKey.AuthAccessRefresh, "Token wird erneuert"),
        (DesktopTextKey.AuthSignedIn, "✓ Angemeldet ({0}, bis {1})"),
        (DesktopTextKey.AuthTokenCorrupt, "✗ Der Token-Speicher ist beschädigt: {0}"),
        (DesktopTextKey.AuthDeviceCodeFailed, "Gerätecode konnte nicht angefordert werden: {0}"),
        (DesktopTextKey.AuthSaveFailed, "Token konnte nicht gespeichert werden: {0}"),
        (DesktopTextKey.AuthDeleteFailed, "✗ Token konnte nicht gelöscht werden: {0}"),
        (DesktopTextKey.AuthRefreshFailed, "✗ Token konnte nicht erneuert werden: {0}"),

        (DesktopTextKey.DeviceTitle, "Diese Station mit GitHub verbinden"),
        (DesktopTextKey.DeviceStep1, "Schritt 1. Diese Adresse im Browser öffnen:"),
        (DesktopTextKey.DeviceStep2, "Schritt 2. Diesen Code eingeben:"),
        (DesktopTextKey.DeviceOpenBrowser, "Öffnen"),
        (DesktopTextKey.DeviceCopyCode, "Kopieren"),
        (DesktopTextKey.DeviceWaiting, "Warten auf die Bestätigung im Browser…"),
        (DesktopTextKey.DeviceCodeCopied, "✓ Code kopiert"),
        (DesktopTextKey.DeviceCopyFailed, "Kopieren fehlgeschlagen: {0}"),
        (DesktopTextKey.DeviceBrowserFailed, "Browser konnte nicht geöffnet werden: {0}"),
        (DesktopTextKey.DeviceAccessDenied, "Der Zugriff wurde auf GitHub verweigert."),
        (DesktopTextKey.DeviceCodeExpired, "Der Code ist abgelaufen. Bitte erneut versuchen."),
        (DesktopTextKey.DeviceError, "Fehler: {0}"),

        (DesktopTextKey.UpdateChecking, "Prüfung…"),
        (DesktopTextKey.CatalogUpdated, "✓ Katalog auf {0} aktualisiert"),
        (DesktopTextKey.CatalogUpdateAvailable, "Ein neuerer signierter Katalog ist verfügbar ({0}). Zum Übernehmen «Aktualisieren» drücken."),
        (DesktopTextKey.TargetDetail, "{0} · {1} · {2} KB · Flash-Beginn {3}"),
        (DesktopTextKey.CatalogDefaultBadge, "STANDARD"),
        (DesktopTextKey.CatalogRevokedBadge, "WIDERRUFEN"),
        (DesktopTextKey.CatalogRemoteBadge, "GITHUB"),
        (DesktopTextKey.FullScreenTooltip, "Vollbild (F11). Verlassen mit F11 oder Esc."),
        (DesktopTextKey.CatalogUpToDate, "✓ Katalog ist aktuell ({0})"),
        (DesktopTextKey.CatalogNoRelease, "Es existiert noch kein Katalog-Release."),
        (DesktopTextKey.CatalogNetworkError, "Netzwerkfehler — bitte die Verbindung prüfen."),
        (DesktopTextKey.CatalogBadSignature, "✗ Die Katalogsignatur ist ungültig. Der Katalog wurde abgelehnt."),
        (DesktopTextKey.CatalogAssetsMissing, "✗ Das Release enthält kein catalog.json samt Signatur."),
        (DesktopTextKey.CatalogParseError, "✗ Der Katalog konnte nicht gelesen werden."),
        (DesktopTextKey.CatalogSourceNotAllowed, "✗ Die Katalogquelle steht nicht auf der Positivliste."),
        (DesktopTextKey.CatalogRollbackRejected, "✗ Abgelehnt: Der Katalog ist älter als der bereits akzeptierte."),
        (DesktopTextKey.AppUpdateAvailable, "✓ Version {0} ist verfügbar"),
        (DesktopTextKey.AppUpToDate, "✓ Die neueste Version ist installiert"),
        (DesktopTextKey.AppNoRelease, "Es existiert noch kein Anwendungs-Release."),
        (DesktopTextKey.AppUpdateParseError, "✗ Die Release-Daten konnten nicht gelesen werden."),

        (DesktopTextKey.CloudDisabledShort, "deaktiviert"),
        (DesktopTextKey.CloudDisabledDetail, "Der Protokoll-Upload ist in den Einstellungen deaktiviert."),
        (DesktopTextKey.CloudUnconfiguredShort, "nicht konfiguriert"),
        (DesktopTextKey.CloudUnconfiguredDetail, "Die GitHub-App für Protokolle ist in diesem Build nicht konfiguriert."),
        (DesktopTextKey.CloudEmptyShort, "leer"),
        (DesktopTextKey.CloudEmptyDetail, "Das lokale Protokoll wurde noch nicht erstellt."),
        (DesktopTextKey.CloudSyncedShort, "✓ synchron"),
        (DesktopTextKey.CloudQueuedShort, "{0} in Warteschlange"),
        (DesktopTextKey.CloudErrorShort, "Fehler"),
        (DesktopTextKey.CloudUploadedAll, "Alle Zeilen hochgeladen."),
        (DesktopTextKey.CloudRowsWaiting, "Zeilen, die auf den Upload warten: {0}"),
        (DesktopTextKey.CloudEnableFirst, "Aktivieren Sie zuerst das Cloud-Protokoll."),
        (DesktopTextKey.CloudKeyMissing, "✗ Schlüsseldatei nicht gefunden: {0}"),
        (DesktopTextKey.CloudUploading, "Upload läuft…"),
        (DesktopTextKey.CloudUploadReport, "✓ Zeilen: {0}; Dateien erstellt: {1}; aktualisiert: {2}; verbleibend: {3}"),

        (DesktopTextKey.HistoryExportBatch, "CSV exportieren (Charge)"),
        (DesktopTextKey.HistoryExportAll, "CSV exportieren (alles)"),
        (DesktopTextKey.RecentAttempts, "Letzte Versuche: {0}"),
        (DesktopTextKey.HistoryBatchEmpty, "Charge {0}: noch keine Versuche."),
        (DesktopTextKey.HistoryBatchCounts, "Charge {0}: gesamt {1}, PASS {2}, FAIL {3} ({4})"),
        (DesktopTextKey.HistoryNeedBatch, "Geben Sie eine Chargen-ID ein, um die Zusammenfassung zu sehen. Zeilen im Protokoll: {0}"),
        (DesktopTextKey.HistoryNoBatches, "Der Chargenmodus ist deaktiviert. Zeilen im Protokoll: {0}"),
        (DesktopTextKey.ExportDone, "✓ {0} Zeilen exportiert → {1}"),
        (DesktopTextKey.ExportBatchesDisabled, "Der Chargenmodus ist deaktiviert — exportieren Sie stattdessen das ganze Protokoll."),
        (DesktopTextKey.ExportBatchRequired, "Geben Sie zuerst eine Chargen-ID ein."),
        (DesktopTextKey.ExportNoDatabase, "Das Protokoll wurde noch nicht erstellt."),
    ];
}
